### ISSUE TITLE
[REVIEW] consider adding automated testing

### ISSUE THREAD

**Issue by earth-chris** [chenyangkang/stemflow#3]
Automated testing is a best practice for open source projects, reducing the risk of software regression through breaking changes. `stemflow` includes a mini_test module that appears to test many parts of the software, but this is run manually. I recommend adding automated tests in CI to verify (and to provide verification to users) that the software continues to function as expected.

**Comment by chenyangkang** [comment]
Thank you for the suggestion! I agree that the test should be automatic.

I have made the mini_test [automatic at each PR and push](https://github.com/chenyangkang/stemflow/blob/main/.github/workflows/run_pytest.yml), testing on Python 3.8, 3.9, and 3.10.

I still kept the `stemflow.manually_testing` module and [mini_test notebook](https://chenyangkang.github.io/stemflow/Examples/00.Mini_test.html) in case any user is interested in it.

Besides, I add pre-commit for code trimming and auto-checking, as well as codecov statistics.

Related PRs: #9, #11 , #12

**Comment by chenyangkang** [comment]
Closing this.
