### ISSUE TITLE
[REVIEW] consider updating contributor guidelines

### ISSUE THREAD

**Issue by earth-chris** [chenyangkang/stemflow#4]
The `stemflow` README contains a sentence on welcoming contributions, but does not specify how those contributions are best made. There are some [nice guides](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) available for providing a contributor guide, and I recommend adding a more detailed guide for users.

**Comment by chenyangkang** [comment]
Thank you for your comments. I added contributing documentation [here](https://github.com/chenyangkang/stemflow/blob/main/docs/CONTRIBUTING.md), as well as [code of conduct](https://github.com/chenyangkang/stemflow/blob/main/docs/CODE_OF_CONDUCT.md) and issue templates.

Related PRs: #5, #7, #8, #13

**Comment by chenyangkang** [comment]
Closing this.
