### ISSUE TITLE
[BUG]plot_gif only work for global and WGS84 currently

### ISSUE THREAD

**Issue by chenyangkang** [chenyangkang/stemflow#48]

**Comment by chenyangkang** [comment]
To install the fixed version:

```py
pip install stemflow@git+https://github.com/chenyangkang/stemflow.git
```

**Comment by chenyangkang** [comment]
Hi @juangallegozamorano, please feel free to comment here if you happen to try the plot_gif function in the fixed version. Thanks!

**Comment by juangallegozamorano** [comment]
I've been busy with other stuff but I will try it in June once I'm more free. Thanks!

**Comment by juangallegozamorano** [comment]
Hi @chenyangkang, I tried and it works :)
